// File generated by Python script, do not modify

typedef bool (* SetFunction)  (int domain_sizes[], int constraints[], int value);
typedef void (* ResetFunction)(int domain_sizes[], int constraints[], int value);

struct Generated {
inline static constexpr int N = 4; 
inline static constexpr int M = 4;

static bool update_domains_set_0_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_0  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_0(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_1  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_1(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_2  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_2(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_3  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_3(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_4  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_4(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_5  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_5(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_6  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_6(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_7  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_7(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_8  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_8(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_9  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_9(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_10  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_10(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_11  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_11(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_12  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_12(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_13  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_13(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_14  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_14(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_0_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_0_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_1_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_1_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_2_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_2_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_3_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_3_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_4_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_4_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_5_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_5_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_6_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_6_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_7_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_7_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_8_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_8_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_9_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_9_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_10_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_10_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_11_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_11_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_12_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_12_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_13_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_13_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_14_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_14_15(int domain_sizes[], int constraints[], int value);

static bool update_domains_set_15_15  (int domain_sizes[], int constraints[], int value);
static void update_domains_reset_15_15(int domain_sizes[], int constraints[], int value);

inline static constexpr const SetFunction table_set[256] = {
	update_domains_set_0_0,
	update_domains_set_1_0,
	update_domains_set_2_0,
	update_domains_set_3_0,
	update_domains_set_4_0,
	update_domains_set_5_0,
	update_domains_set_6_0,
	update_domains_set_7_0,
	update_domains_set_8_0,
	update_domains_set_9_0,
	update_domains_set_10_0,
	update_domains_set_11_0,
	update_domains_set_12_0,
	update_domains_set_13_0,
	update_domains_set_14_0,
	update_domains_set_15_0,
	update_domains_set_0_1,
	update_domains_set_1_1,
	update_domains_set_2_1,
	update_domains_set_3_1,
	update_domains_set_4_1,
	update_domains_set_5_1,
	update_domains_set_6_1,
	update_domains_set_7_1,
	update_domains_set_8_1,
	update_domains_set_9_1,
	update_domains_set_10_1,
	update_domains_set_11_1,
	update_domains_set_12_1,
	update_domains_set_13_1,
	update_domains_set_14_1,
	update_domains_set_15_1,
	update_domains_set_0_2,
	update_domains_set_1_2,
	update_domains_set_2_2,
	update_domains_set_3_2,
	update_domains_set_4_2,
	update_domains_set_5_2,
	update_domains_set_6_2,
	update_domains_set_7_2,
	update_domains_set_8_2,
	update_domains_set_9_2,
	update_domains_set_10_2,
	update_domains_set_11_2,
	update_domains_set_12_2,
	update_domains_set_13_2,
	update_domains_set_14_2,
	update_domains_set_15_2,
	update_domains_set_0_3,
	update_domains_set_1_3,
	update_domains_set_2_3,
	update_domains_set_3_3,
	update_domains_set_4_3,
	update_domains_set_5_3,
	update_domains_set_6_3,
	update_domains_set_7_3,
	update_domains_set_8_3,
	update_domains_set_9_3,
	update_domains_set_10_3,
	update_domains_set_11_3,
	update_domains_set_12_3,
	update_domains_set_13_3,
	update_domains_set_14_3,
	update_domains_set_15_3,
	update_domains_set_0_4,
	update_domains_set_1_4,
	update_domains_set_2_4,
	update_domains_set_3_4,
	update_domains_set_4_4,
	update_domains_set_5_4,
	update_domains_set_6_4,
	update_domains_set_7_4,
	update_domains_set_8_4,
	update_domains_set_9_4,
	update_domains_set_10_4,
	update_domains_set_11_4,
	update_domains_set_12_4,
	update_domains_set_13_4,
	update_domains_set_14_4,
	update_domains_set_15_4,
	update_domains_set_0_5,
	update_domains_set_1_5,
	update_domains_set_2_5,
	update_domains_set_3_5,
	update_domains_set_4_5,
	update_domains_set_5_5,
	update_domains_set_6_5,
	update_domains_set_7_5,
	update_domains_set_8_5,
	update_domains_set_9_5,
	update_domains_set_10_5,
	update_domains_set_11_5,
	update_domains_set_12_5,
	update_domains_set_13_5,
	update_domains_set_14_5,
	update_domains_set_15_5,
	update_domains_set_0_6,
	update_domains_set_1_6,
	update_domains_set_2_6,
	update_domains_set_3_6,
	update_domains_set_4_6,
	update_domains_set_5_6,
	update_domains_set_6_6,
	update_domains_set_7_6,
	update_domains_set_8_6,
	update_domains_set_9_6,
	update_domains_set_10_6,
	update_domains_set_11_6,
	update_domains_set_12_6,
	update_domains_set_13_6,
	update_domains_set_14_6,
	update_domains_set_15_6,
	update_domains_set_0_7,
	update_domains_set_1_7,
	update_domains_set_2_7,
	update_domains_set_3_7,
	update_domains_set_4_7,
	update_domains_set_5_7,
	update_domains_set_6_7,
	update_domains_set_7_7,
	update_domains_set_8_7,
	update_domains_set_9_7,
	update_domains_set_10_7,
	update_domains_set_11_7,
	update_domains_set_12_7,
	update_domains_set_13_7,
	update_domains_set_14_7,
	update_domains_set_15_7,
	update_domains_set_0_8,
	update_domains_set_1_8,
	update_domains_set_2_8,
	update_domains_set_3_8,
	update_domains_set_4_8,
	update_domains_set_5_8,
	update_domains_set_6_8,
	update_domains_set_7_8,
	update_domains_set_8_8,
	update_domains_set_9_8,
	update_domains_set_10_8,
	update_domains_set_11_8,
	update_domains_set_12_8,
	update_domains_set_13_8,
	update_domains_set_14_8,
	update_domains_set_15_8,
	update_domains_set_0_9,
	update_domains_set_1_9,
	update_domains_set_2_9,
	update_domains_set_3_9,
	update_domains_set_4_9,
	update_domains_set_5_9,
	update_domains_set_6_9,
	update_domains_set_7_9,
	update_domains_set_8_9,
	update_domains_set_9_9,
	update_domains_set_10_9,
	update_domains_set_11_9,
	update_domains_set_12_9,
	update_domains_set_13_9,
	update_domains_set_14_9,
	update_domains_set_15_9,
	update_domains_set_0_10,
	update_domains_set_1_10,
	update_domains_set_2_10,
	update_domains_set_3_10,
	update_domains_set_4_10,
	update_domains_set_5_10,
	update_domains_set_6_10,
	update_domains_set_7_10,
	update_domains_set_8_10,
	update_domains_set_9_10,
	update_domains_set_10_10,
	update_domains_set_11_10,
	update_domains_set_12_10,
	update_domains_set_13_10,
	update_domains_set_14_10,
	update_domains_set_15_10,
	update_domains_set_0_11,
	update_domains_set_1_11,
	update_domains_set_2_11,
	update_domains_set_3_11,
	update_domains_set_4_11,
	update_domains_set_5_11,
	update_domains_set_6_11,
	update_domains_set_7_11,
	update_domains_set_8_11,
	update_domains_set_9_11,
	update_domains_set_10_11,
	update_domains_set_11_11,
	update_domains_set_12_11,
	update_domains_set_13_11,
	update_domains_set_14_11,
	update_domains_set_15_11,
	update_domains_set_0_12,
	update_domains_set_1_12,
	update_domains_set_2_12,
	update_domains_set_3_12,
	update_domains_set_4_12,
	update_domains_set_5_12,
	update_domains_set_6_12,
	update_domains_set_7_12,
	update_domains_set_8_12,
	update_domains_set_9_12,
	update_domains_set_10_12,
	update_domains_set_11_12,
	update_domains_set_12_12,
	update_domains_set_13_12,
	update_domains_set_14_12,
	update_domains_set_15_12,
	update_domains_set_0_13,
	update_domains_set_1_13,
	update_domains_set_2_13,
	update_domains_set_3_13,
	update_domains_set_4_13,
	update_domains_set_5_13,
	update_domains_set_6_13,
	update_domains_set_7_13,
	update_domains_set_8_13,
	update_domains_set_9_13,
	update_domains_set_10_13,
	update_domains_set_11_13,
	update_domains_set_12_13,
	update_domains_set_13_13,
	update_domains_set_14_13,
	update_domains_set_15_13,
	update_domains_set_0_14,
	update_domains_set_1_14,
	update_domains_set_2_14,
	update_domains_set_3_14,
	update_domains_set_4_14,
	update_domains_set_5_14,
	update_domains_set_6_14,
	update_domains_set_7_14,
	update_domains_set_8_14,
	update_domains_set_9_14,
	update_domains_set_10_14,
	update_domains_set_11_14,
	update_domains_set_12_14,
	update_domains_set_13_14,
	update_domains_set_14_14,
	update_domains_set_15_14,
	update_domains_set_0_15,
	update_domains_set_1_15,
	update_domains_set_2_15,
	update_domains_set_3_15,
	update_domains_set_4_15,
	update_domains_set_5_15,
	update_domains_set_6_15,
	update_domains_set_7_15,
	update_domains_set_8_15,
	update_domains_set_9_15,
	update_domains_set_10_15,
	update_domains_set_11_15,
	update_domains_set_12_15,
	update_domains_set_13_15,
	update_domains_set_14_15,
	update_domains_set_15_15,
};
inline static constexpr const ResetFunction table_reset[256] = {
	update_domains_reset_0_0,
	update_domains_reset_1_0,
	update_domains_reset_2_0,
	update_domains_reset_3_0,
	update_domains_reset_4_0,
	update_domains_reset_5_0,
	update_domains_reset_6_0,
	update_domains_reset_7_0,
	update_domains_reset_8_0,
	update_domains_reset_9_0,
	update_domains_reset_10_0,
	update_domains_reset_11_0,
	update_domains_reset_12_0,
	update_domains_reset_13_0,
	update_domains_reset_14_0,
	update_domains_reset_15_0,
	update_domains_reset_0_1,
	update_domains_reset_1_1,
	update_domains_reset_2_1,
	update_domains_reset_3_1,
	update_domains_reset_4_1,
	update_domains_reset_5_1,
	update_domains_reset_6_1,
	update_domains_reset_7_1,
	update_domains_reset_8_1,
	update_domains_reset_9_1,
	update_domains_reset_10_1,
	update_domains_reset_11_1,
	update_domains_reset_12_1,
	update_domains_reset_13_1,
	update_domains_reset_14_1,
	update_domains_reset_15_1,
	update_domains_reset_0_2,
	update_domains_reset_1_2,
	update_domains_reset_2_2,
	update_domains_reset_3_2,
	update_domains_reset_4_2,
	update_domains_reset_5_2,
	update_domains_reset_6_2,
	update_domains_reset_7_2,
	update_domains_reset_8_2,
	update_domains_reset_9_2,
	update_domains_reset_10_2,
	update_domains_reset_11_2,
	update_domains_reset_12_2,
	update_domains_reset_13_2,
	update_domains_reset_14_2,
	update_domains_reset_15_2,
	update_domains_reset_0_3,
	update_domains_reset_1_3,
	update_domains_reset_2_3,
	update_domains_reset_3_3,
	update_domains_reset_4_3,
	update_domains_reset_5_3,
	update_domains_reset_6_3,
	update_domains_reset_7_3,
	update_domains_reset_8_3,
	update_domains_reset_9_3,
	update_domains_reset_10_3,
	update_domains_reset_11_3,
	update_domains_reset_12_3,
	update_domains_reset_13_3,
	update_domains_reset_14_3,
	update_domains_reset_15_3,
	update_domains_reset_0_4,
	update_domains_reset_1_4,
	update_domains_reset_2_4,
	update_domains_reset_3_4,
	update_domains_reset_4_4,
	update_domains_reset_5_4,
	update_domains_reset_6_4,
	update_domains_reset_7_4,
	update_domains_reset_8_4,
	update_domains_reset_9_4,
	update_domains_reset_10_4,
	update_domains_reset_11_4,
	update_domains_reset_12_4,
	update_domains_reset_13_4,
	update_domains_reset_14_4,
	update_domains_reset_15_4,
	update_domains_reset_0_5,
	update_domains_reset_1_5,
	update_domains_reset_2_5,
	update_domains_reset_3_5,
	update_domains_reset_4_5,
	update_domains_reset_5_5,
	update_domains_reset_6_5,
	update_domains_reset_7_5,
	update_domains_reset_8_5,
	update_domains_reset_9_5,
	update_domains_reset_10_5,
	update_domains_reset_11_5,
	update_domains_reset_12_5,
	update_domains_reset_13_5,
	update_domains_reset_14_5,
	update_domains_reset_15_5,
	update_domains_reset_0_6,
	update_domains_reset_1_6,
	update_domains_reset_2_6,
	update_domains_reset_3_6,
	update_domains_reset_4_6,
	update_domains_reset_5_6,
	update_domains_reset_6_6,
	update_domains_reset_7_6,
	update_domains_reset_8_6,
	update_domains_reset_9_6,
	update_domains_reset_10_6,
	update_domains_reset_11_6,
	update_domains_reset_12_6,
	update_domains_reset_13_6,
	update_domains_reset_14_6,
	update_domains_reset_15_6,
	update_domains_reset_0_7,
	update_domains_reset_1_7,
	update_domains_reset_2_7,
	update_domains_reset_3_7,
	update_domains_reset_4_7,
	update_domains_reset_5_7,
	update_domains_reset_6_7,
	update_domains_reset_7_7,
	update_domains_reset_8_7,
	update_domains_reset_9_7,
	update_domains_reset_10_7,
	update_domains_reset_11_7,
	update_domains_reset_12_7,
	update_domains_reset_13_7,
	update_domains_reset_14_7,
	update_domains_reset_15_7,
	update_domains_reset_0_8,
	update_domains_reset_1_8,
	update_domains_reset_2_8,
	update_domains_reset_3_8,
	update_domains_reset_4_8,
	update_domains_reset_5_8,
	update_domains_reset_6_8,
	update_domains_reset_7_8,
	update_domains_reset_8_8,
	update_domains_reset_9_8,
	update_domains_reset_10_8,
	update_domains_reset_11_8,
	update_domains_reset_12_8,
	update_domains_reset_13_8,
	update_domains_reset_14_8,
	update_domains_reset_15_8,
	update_domains_reset_0_9,
	update_domains_reset_1_9,
	update_domains_reset_2_9,
	update_domains_reset_3_9,
	update_domains_reset_4_9,
	update_domains_reset_5_9,
	update_domains_reset_6_9,
	update_domains_reset_7_9,
	update_domains_reset_8_9,
	update_domains_reset_9_9,
	update_domains_reset_10_9,
	update_domains_reset_11_9,
	update_domains_reset_12_9,
	update_domains_reset_13_9,
	update_domains_reset_14_9,
	update_domains_reset_15_9,
	update_domains_reset_0_10,
	update_domains_reset_1_10,
	update_domains_reset_2_10,
	update_domains_reset_3_10,
	update_domains_reset_4_10,
	update_domains_reset_5_10,
	update_domains_reset_6_10,
	update_domains_reset_7_10,
	update_domains_reset_8_10,
	update_domains_reset_9_10,
	update_domains_reset_10_10,
	update_domains_reset_11_10,
	update_domains_reset_12_10,
	update_domains_reset_13_10,
	update_domains_reset_14_10,
	update_domains_reset_15_10,
	update_domains_reset_0_11,
	update_domains_reset_1_11,
	update_domains_reset_2_11,
	update_domains_reset_3_11,
	update_domains_reset_4_11,
	update_domains_reset_5_11,
	update_domains_reset_6_11,
	update_domains_reset_7_11,
	update_domains_reset_8_11,
	update_domains_reset_9_11,
	update_domains_reset_10_11,
	update_domains_reset_11_11,
	update_domains_reset_12_11,
	update_domains_reset_13_11,
	update_domains_reset_14_11,
	update_domains_reset_15_11,
	update_domains_reset_0_12,
	update_domains_reset_1_12,
	update_domains_reset_2_12,
	update_domains_reset_3_12,
	update_domains_reset_4_12,
	update_domains_reset_5_12,
	update_domains_reset_6_12,
	update_domains_reset_7_12,
	update_domains_reset_8_12,
	update_domains_reset_9_12,
	update_domains_reset_10_12,
	update_domains_reset_11_12,
	update_domains_reset_12_12,
	update_domains_reset_13_12,
	update_domains_reset_14_12,
	update_domains_reset_15_12,
	update_domains_reset_0_13,
	update_domains_reset_1_13,
	update_domains_reset_2_13,
	update_domains_reset_3_13,
	update_domains_reset_4_13,
	update_domains_reset_5_13,
	update_domains_reset_6_13,
	update_domains_reset_7_13,
	update_domains_reset_8_13,
	update_domains_reset_9_13,
	update_domains_reset_10_13,
	update_domains_reset_11_13,
	update_domains_reset_12_13,
	update_domains_reset_13_13,
	update_domains_reset_14_13,
	update_domains_reset_15_13,
	update_domains_reset_0_14,
	update_domains_reset_1_14,
	update_domains_reset_2_14,
	update_domains_reset_3_14,
	update_domains_reset_4_14,
	update_domains_reset_5_14,
	update_domains_reset_6_14,
	update_domains_reset_7_14,
	update_domains_reset_8_14,
	update_domains_reset_9_14,
	update_domains_reset_10_14,
	update_domains_reset_11_14,
	update_domains_reset_12_14,
	update_domains_reset_13_14,
	update_domains_reset_14_14,
	update_domains_reset_15_14,
	update_domains_reset_0_15,
	update_domains_reset_1_15,
	update_domains_reset_2_15,
	update_domains_reset_3_15,
	update_domains_reset_4_15,
	update_domains_reset_5_15,
	update_domains_reset_6_15,
	update_domains_reset_7_15,
	update_domains_reset_8_15,
	update_domains_reset_9_15,
	update_domains_reset_10_15,
	update_domains_reset_11_15,
	update_domains_reset_12_15,
	update_domains_reset_13_15,
	update_domains_reset_14_15,
	update_domains_reset_15_15,
};
};
